#!/bin/bash

export SCRIPT_DIR=$(dirname "$0")
export CONFIG="$1"

keychain_unlocked=false
default_keychain=

config ()
{
    # A bootstrap script to run before building.
    #
    # If this file does not exist, it is not considered an error.
    : ${BOOTSTRAP="$SCRIPT_DIR/bootstrap"}
    
    export BOOTSTRAP 
}

print_title ()
{
    echo ""
    echo "====== 🍊 "$1" 🍊 ======"
    export CURRENT_ACTION="$1"
}

print_title_fail ()
{
    echo "====== ❌ "$1" ❌ ======"
}

fail ()
{
    export EXIT_CODE=$1
    print_title_fail "Failed $CURRENT_ACTION"
    exit $EXIT_CODE
}

main ()
{
    config

    if [ -f "$BOOTSTRAP" ]
    then
        print_title "Bootstrapping"
        "$BOOTSTRAP" || exit $?
    fi

    INFO_PLIST_PATH="$XCSCHEME/Info.plist"

    print_title "Configuring"
    if [ -f "$CONFIG" ]
    then
        . "$CONFIG" || fail $?
    else
        echo "*** Couldn't find config file"
        fail 1
    fi

    export BUILD_PATH="$WORKSPACE"/build

    export XCPRETTY_FLAGS="-s"
    [ "$COLORIZED_OUTPUT" != True ] || export XCPRETTY_FLAGS="-c"

    export CURL_FLAGS="-sS"
    export CURL_FLAGS="--progress"

    [ "$KEYCHAIN" == True ] && setup_keychain
    [ -e "$PROFILE_PATH" ] && import_provisioning_profile
    [ "$RETRIEVE_PROFILE" == True ] && setup_profile
    [ "$COCOAPODS" == True ] && setup_pods
    clean_artifacts
    [ "$INCREASE_BUILD_NUMBER" == True ] && increase_build_number

    get_build_number

    export ARTIFACT_NAME="$XCSCHEME-$CURRENT_VERSION_STRING-$CURRENT_BUILD_NUMBER"
    export ARCHIVE_PATH="$BUILD_PATH"/"$ARTIFACT_NAME".xcarchive
    export IPA_PATH="$BUILD_PATH"/"$ARTIFACT_NAME".ipa
    export DSYM_PATH="$ARCHIVE_PATH"/dSYMs/$XCSCHEME.app.dSYM
    export DSYM_ZIP_PATH="$BUILD_PATH"/"$ARTIFACT_NAME".app.dSYM.zip
    export IPA_ZIP_PATH="$BUILD_PATH"/"$ARTIFACT_NAME".zip

    build_archive
    [ "$TEST" == True ] && test_application
    [ "$EXPORT_IPA" == True ] && export_ipa
    [ "$ZIP_ARTIFACTS" == True ] && zip_artifacts
    [ "$CRASHLYTICS" == True ] && submit_to_crashlytics
    [ "$KEYCHAIN" == True ] && reset_keychain
}

function uuid_from_profile
{
    grep -aA1 UUID "$1" | grep -o "[-a-zA-Z0-9]\{36\}"
}

import_provisioning_profile ()
{
    # Import Provisioning Profile
    print_title "Archiving DSYMs"

    export PROFILE_UUID=$(uuid_from_profile "$PROFILE_PATH")

    if [ -n "$PROFILE_UUID" ]
    then             
        echo "Installing profile \"$PROFILE_PATH\" ($PROFILE_UUID)"
        cp -f "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision" || fail $?
    else
        echo "*** No UUID found in $PROVISIONING_PROFILE"
    fi
}

setup_profile ()
{
    print_title "Setting Up Profile"
    WD=$(pwd)
    mkdir -p "$BUILD_PATH"/profiles
    cd "$BUILD_PATH"/profiles

    rm -rf *.mobileprovision

    set -o pipefail && PROVISIONING_PROFILE=$(ios profiles:download --type distribution "$PROVISIONING_PROFILE_NAME" -u "$APPLE_DEVELOPER_USERNAME" -p "$APPLE_DEVELOPER_PASSWORD" --team "$APPLE_DEVELOPER_TEAM" | grep -Eoh "[A-Za-z0-9_]+\.mobileprovision") || fail $?
    PROFILE_UUID=$(uuid_from_profile "$PROVISIONING_PROFILE")

    export PROFILE
    export PROFILE_UUID

    if [ -n "$PROFILE_UUID" ]
    then             
        echo "Installing profile $PROVISIONING_PROFILE ($PROFILE_UUID)"
        cp -f "$PROVISIONING_PROFILE" "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision" || fail $?
    else
        echo "*** No UUID found in $PROVISIONING_PROFILE"
    fi

    cd "$WD"
}

# Generic helper for killing the script when
# something goes wrong. It prints the error
# message and exists with error code.
function die
{
    [ $# -gt 0 ] && echo "Error: $@" >&2
    exit 1
}

# Opens the keychain so that it can be used for code signing.
# Keychain is set as default keychain because xcodebuild 
# implicitly uses default keychain for code signing and does not
# allow to explicitly define another.
function setup_keychain
{

    echo "Setting up keychain"

    if [ ! -f $KEYCHAIN_PATH ]; then
        die "Keychain File not found"
    fi

    # Rememeber the default keychain that was set previously
    # Here, the security will print a string like this:
    #        "/Users/me/Library/Keychains/login.keychain"
    # Since we want to get rid of quotes and spaces we pipe the output into two seds
    # The first sed cuts off everything before the first quote (with quote included)
    # The second sed cuts off everything after the second quote (with quote included)
    default_keychain=`security default-keychain -d user | sed 's/\ *\"//' | sed 's/\".*//'`

    # Reset the default keychain only if it is not so yet
    if [ "$default_keychain" != "$KEYCHAIN_PATH" ]; then

        # First, get the list of current visible keychains
        # Here, the security will print a multiline string with like this:
        #         "/Users/me/Library/Keychains/login.keychain"
        #         "/Users/me/Library/Keychains/custom.keychain"
        # Since we want to get rid of quotes and spaces we pipe the output into two seds
        # The first sed cuts off everything before the first quote (with quote included)
        # The second sed cuts off everything after the second quote (with quote included)
        keychains=`security list-keychains -d user | sed 's/\ *\"//' | sed 's/\".*//'`

        if [[ $keychains == *"$KEYCHAIN_PATH"* ]]; then

            # Keychain was already in the list. Do not attempt to add it again
            # Otherwise next time we list keychains, our keychain will be duplicated
            # and to remove it you'll need to executre remove as many times as
            # that keychain appears in the list
            echo "$KEYCHAIN_PATH is already in the list"
        else
            echo "Adding $KEYCHAIN_PATH to the list of available keychains..."

            # Append our new keychain to the list
            keychains="$keychains $KEYCHAIN_PATH"

            echo "Setting list of available keychains to"
            for line in $keychains; do
                echo $line
            done 

            # Set the keychain search list to our augmented list
            # (This command will reset the keychains that you normally see in the sidebar of Keychain Access)
            security list-keychains -d user -s $keychains
        fi


        echo "Setting default keychain to $KEYCHAIN_PATH..."
        # Set the default keychain to our desired one
        # This is needed because xcodebuild implicitly uses default keychain for code signing and does not
        # allow to explicitly define another.
        security default-keychain -d user -s "$KEYCHAIN_PATH" || die "Failed to set $KEYCHAIN_PATH as default"
    else
        echo "$KEYCHAIN_PATH is already the default keychain"
    fi

    # Unlock Keychain
    echo "Unlocking Keychain..."
    security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH" || die "Failed to unlock $KEYCHAIN_PATH"
    keychain_unlocked=true
    echo "Keychain unlocked"

    # This command assigns the setting to lock keychain when system sleeps
    # We do not want to adjust any settings for the default keychain
    if [ "$default_keychain" != "$KEYCHAIN_PATH" ]; then
        echo "Updating keychain settings..."    
        security set-keychain-setting -l "$KEYCHAIN_PATH"
    fi
    echo "Keychain info:"
    output="$(security show-keychain-info $KEYCHAIN_PATH 2>&1)"
    echo "$output"
}

# Closes the keychain if it was manipulated during the script execution.
# This function locks the keychain and resets the default keychain to the 
# one that has been default previously.
function reset_keychain
{
    echo "Rolling back keychain state"

    # Reset default keychain only if they are different
    if [ "$default_keychain" != "$KEYCHAIN_PATH" ]; then

        if [ $keychain_unlocked = true ]; then
            echo "Locking $KEYCHAIN_PATH..."
            security lock-keychain "$KEYCHAIN_PATH" || echo "Failed to lock $KEYCHAIN_PATH"
        fi

        echo "Resetting default keychain to $default_keychain..."
        security default-keychain -d user -s "$default_keychain" || echo "Failed to set $default_keychain as default"
    fi
}

setup_pods ()
{
    print_title "Setting Up Pods"
    pod repo update || fail $?;
    pod update || fail $?;
}

clean_artifacts ()
{
    # Clean Previuos Artifacts
    print_title "Cleaning Artifacts"
    rm -rf "$BUILD_PATH"/*.xcarchive || fail $?;
    rm -f "$BUILD_PATH"/*.ipa || fail $?;
    rm -f "$BUILD_PATH"/*.zip || fail $?;
    rm -f "$BUILD_PATH"/tf_upload.log || fail $?;
}

increase_build_number ()
{
    # Increase build number
    print_title "Increasing Build Number"

    if [ -z "$EXTERNAL_BUILD_NUMBER" ]
    then
        set -o pipefail && PREV_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$INFO_PLIST_PATH") || fail $?
        CURRENT_BUILD_NUMBER=$((PREV_BUILD_NUMBER + 1))
        echo "*** Previuos Build #: $PREV_BUILD_NUMBER"
    else
        CURRENT_BUILD_NUMBER="$EXTERNAL_BUILD_NUMBER"
    fi

    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CURRENT_BUILD_NUMBER" "$INFO_PLIST_PATH" || fail $?;
}

get_build_number ()
{
	# Retrieve build number
	print_title "Retrieving Build Number"

	export CURRENT_VERSION_STRING=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$INFO_PLIST_PATH") || fail $?
	export CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$INFO_PLIST_PATH") || fail $?

	echo "*** Current Version #: $CURRENT_VERSION_STRING $CURRENT_BUILD_NUMBER"
}

build_archive ()
{
    # Build
    print_title "Building Application"

    set -o pipefail && (xcodebuild -scheme "$XCSCHEME" -workspace "$XCWORKSPACE" -configuration "$BUILD_CONFIGURATION" clean archive -archivePath "$ARCHIVE_PATH" "CODE_SIGN_IDENTITY=$CODE_SIGNING_IDENTITY" "PROVISIONING_PROFILE=$PROFILE_UUID" | xcpretty $XCPRETTY_FLAGS) || fail $?;
}

test_application ()
{
    # Test
    print_title "Testing Application"

    set -o pipefail && (xcodebuild -scheme "$XCSCHEME" -workspace "$XCWORKSPACE" -configuration "$BUILD_CONFIGURATION" -sdk iphonesimulator test | xcpretty $XCPRETTY_FLAGS -t -r junit --output "$BUILD_PATH"/junit.xml) || fail $?;
}

export_ipa ()
{
    # Export IPA
    print_title "Creating IPA File"

    xcodebuild -exportArchive -exportFormat ipa -archivePath "$ARCHIVE_PATH" -exportPath "$IPA_PATH" -exportProvisioningProfile "$PROVISIONING_PROFILE_NAME" || fail $?;
}

prepare_dsym ()
{
    # Prepare DSYM File
    print_title "Archiving DSYMs"

    zip -rj $DSYM_ZIP_PATH "$DSYM_PATH" || fail $?;
}

zip_artifacts ()
{
	# Zip DSYM and IPA.
	print_title "Archiving Build Artifacts"
	
	ABS_WORK_DIR=$(pwd)

	pushd $DSYM_PATH/..
	zip -r "$ABS_WORK_DIR"/"$IPA_ZIP_PATH" "$XCSCHEME".app.dSYM || fail $?;
	popd
	zip -j "$IPA_ZIP_PATH" "$IPA_PATH" || fail $?;
}

submit_to_crashlytics ()
{
    # Submit to Crashlytics
    print_title "Uploading to Crashlytics"

    echo "*** File: $IPA_PATH"

    CRASHLYTICS_EMAILS_OPT="-emails "$CRASHLYTICS_EMAILS""
    CRASHLYTICS_NOTES_PATH_OPT="-notesPath "$CRASHLYTICS_NOTES_PATH""
    CRASHLYTICS_GROUP_ALIASES_OPT="-groupAliases "$CRASHLYTICS_GROUP_ALIASES""
    CRASHLYTICS_NOTIFICATIONS_OPT="-notifications "$CRASHLYTICS_NOTIFICATIONS""

    #Crashlytics uses this to point to the specific keychain we're using
    CODE_SIGN_KEYCHAIN="$KEYCHAIN_PATH"

    "$CRASHLYTICS_FRAMEWORK_PATH"/submit "$CRASHLYTICS_API_KEY" "$CRASHLYTICS_BUILD_SECRET" -ipaPath "$IPA_PATH" $CRASHLYTICS_EMAILS_OPT $CRASHLYTICS_NOTES_PATH_OPT $CRASHLYTICS_GROUP_ALIASES_OPT $CRASHLYTICS_NOTIFICATIONS_OPT
}

trap reset_keychain EXIT

main
exit 0